repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # Hook to remove trailing whitespace
      - id: trailing-whitespace
      # Hook to ensure files end with a newline
      - id: end-of-file-fixer
      # Hook to check for large files being added to the repo
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      # Hook to format code using Black with PEP 8 standard
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
      # Lints the code and checks for various PEP 8 issues
      - id: flake8
        args:
          - >-
            --ignore=
              B001,B006,B008
              C901,
              E121,E126,E127,E128,E131,E203,E226,E251,E261,E262,E265,E401,E402,E501,E502,E722,
              F401,F401,F403,F403,F405,F405,F541,F541,
              N801,N802,N803,N806,N812,N814,N814,
              SIM102,SIM105,SIM106,SIM110,SIM118,SIM210,SIM300,
              T001,
              W292,W292,W391,W503,W503,W504,W504, W605
              TYP001,TYP002,
              T201,
              N815,
              F601
        additional_dependencies:
          # Checking naming conventions
          - pep8-naming

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      # Hook to sort imports
      - id: isort

exclude: ^(src/config/(prompts|tools)/.*|\.gitignore|Dockerfile)$
